
import { Competition, Category } from './types';

export const COMPETITIONS: Competition[] = [
  // --- Mathematics ---
  {
    id: 'math-1',
    name: 'Southeast Asian Mathematical Olympiad',
    shortName: 'SEAMO',
    category: Category.MATHEMATICS,
    description: 'A regional mathematics competition organized in Singapore focusing on logical reasoning and creative problem-solving.',
    date: 'Every October',
    monthStr: 'October',
    duration: '90 minutes',
    language: 'English',
    content: 'Algebra, geometry, number theory, logical reasoning.',
    location: 'Both online and offline (authorized centers).',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: 'Total 140 points; gold, silver, and bronze medals based on percentile.',
    organizer: 'SEAMO Organizing Committee',
    registrationDeadline: 'Late September',
    resultDate: 'November',
    materials: [
      { title: 'SEAMO 2023 Past Paper (Grade 10)', url: '#' },
      { title: 'SEAMO Syllabus Guide', url: '#' }
    ]
  },
  {
    id: 'math-2',
    name: 'United Kingdom Mathematics Trust',
    shortName: 'UKMT',
    category: Category.MATHEMATICS,
    description: 'The most influential math competitions in the UK, including JMC, IMC, and SMC.',
    date: 'Each October',
    monthStr: 'October',
    duration: '60 minutes',
    language: 'English',
    content: 'Multiple-choice problems involving algebra, geometry, number theory, and logic.',
    location: 'Offline (school-organized).',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: '135 total points; gold, silver, and bronze certificates awarded.',
    organizer: 'United Kingdom Mathematics Trust',
    registrationDeadline: 'Early September',
    resultDate: 'November',
    website: 'https://www.ukmt.org.uk',
    materials: [
        { title: 'SMC 2023 Solutions', url: '#' },
        { title: 'SMC 2022 Past Paper', url: '#' }
    ]
  },
  {
    id: 'math-3',
    name: 'British Mathematical Olympiad',
    shortName: 'BMO',
    category: Category.MATHEMATICS,
    description: 'High-level exam for top UKMT performers, used to select the UK IMO team.',
    date: 'Nov (BMO1) / Jan (BMO2)',
    monthStr: 'November',
    duration: '3.5 hours each',
    language: 'English',
    content: 'Proof-based problems in number theory, geometry, combinatorics, and algebra.',
    location: 'Offline (schools or test centers).',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: '6 questions, 10 points each, total 60 points.',
    organizer: 'UKMT',
    registrationDeadline: 'Qualification based (Invitation only)',
    resultDate: 'January'
  },
  {
    id: 'math-4',
    name: 'Mathematical Challenge for Girls',
    shortName: 'MCG',
    category: Category.MATHEMATICS,
    description: 'Encourages female participation in mathematics through a problem-solving competition designed for girls.',
    date: 'October',
    monthStr: 'October',
    duration: '90 minutes',
    language: 'English',
    content: 'Short-answer and reasoning problems.',
    location: 'Offline (schools or test centers).',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: 'Awards based on total score.',
  },
  {
    id: 'math-5',
    name: 'Euclid Mathematics Contest',
    shortName: 'Euclid',
    category: Category.MATHEMATICS,
    description: 'Hosted by the University of Waterloo, one of Canada’s most prestigious math competitions.',
    date: 'April',
    monthStr: 'April',
    duration: '150 minutes',
    language: 'English or French',
    content: '10 problems (short and long answers) covering algebra, geometry, sequences, and functions.',
    location: 'Online or offline (authorized centers).',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: '100 points in total; partial credit available.',
    organizer: 'University of Waterloo'
  },
  {
    id: 'math-6',
    name: 'Canadian Open Mathematics Challenge',
    shortName: 'COMC',
    category: Category.MATHEMATICS,
    description: 'Organized by the Canadian Mathematical Society, serves as the national qualifier for the Canadian Mathematical Olympiad.',
    date: 'November',
    monthStr: 'November',
    duration: '150 minutes',
    language: 'English or French',
    content: 'Multiple-choice and written-answer questions.',
    location: 'Offline.',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: '80 points total; awards based on national ranking.',
  },
  {
    id: 'math-7',
    name: 'Canadian Intermediate and Senior Mathematics Contests',
    shortName: 'CIMC / CSMC',
    category: Category.MATHEMATICS,
    description: 'Mid-level challenges hosted by the University of Waterloo for high school students of different grades.',
    date: 'November',
    monthStr: 'November',
    duration: '120 minutes',
    language: 'English or French',
    content: 'Algebra, geometry, probability, number theory.',
    location: 'Online or offline.',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: 'Total of 80 points.',
    organizer: 'University of Waterloo'
  },
  {
    id: 'math-8',
    name: 'Canadian Mathematical Olympiad',
    shortName: 'CMO / CJMO',
    category: Category.MATHEMATICS,
    description: 'Top COMC performers qualify for the CMO or CJMO, Canada’s highest-level math contests selecting the IMO team.',
    date: 'March',
    monthStr: 'March',
    duration: '3 hours',
    language: 'English or French',
    content: 'Proof-based Olympiad-level questions.',
    location: 'Offline (authorized centers).',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: '6 problems, 10 points each, total 60 points.',
  },
  {
    id: 'math-9',
    name: 'Australian Mathematics Competition',
    shortName: 'AMC',
    category: Category.MATHEMATICS,
    description: 'One of the world’s largest mathematics contests, attracting students from over 60 countries.',
    date: 'September',
    monthStr: 'September',
    duration: '75 minutes',
    language: 'English',
    content: 'Logical reasoning and problem-solving in various mathematical fields.',
    location: 'Online or offline.',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: '120 points total; top 1% receive gold awards.',
    organizer: 'Australian Maths Trust',
    registrationDeadline: 'August 15',
    resultDate: 'Late October'
  },
  {
    id: 'math-10',
    name: 'Kangaroo Math Competition',
    shortName: 'Kangaroo',
    category: Category.MATHEMATICS,
    description: 'Originating in France, Kangaroo Math promotes creative mathematical thinking worldwide.',
    date: 'March',
    monthStr: 'March',
    duration: '75 minutes',
    language: 'English',
    content: 'Logical and geometric reasoning.',
    location: 'Online or Offline.',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: 'Based on number of correct answers.',
  },
  {
    id: 'math-11',
    name: 'American Mathematics Competitions',
    shortName: 'AMC 10 / 12',
    category: Category.MATHEMATICS,
    description: 'National math competitions in the USA testing problem-solving and reasoning.',
    date: 'November 14', 
    monthStr: 'November',
    duration: '75 minutes',
    language: 'English',
    content: 'Algebra, geometry, number theory, combinatorics, logical reasoning.',
    location: 'Online or at participating schools.',
    format: 'Individual, multiple-choice.',
    participation: 'Individual.',
    scoring: 'Based on number of correct answers; top scorers qualify for AIME.',
    organizer: 'Mathematical Association of America (MAA)',
    registrationDeadline: 'Late October',
    resultDate: 'December',
    website: 'https://www.maa.org/math-competitions'
  },
  {
    id: 'math-12',
    name: 'American Invitational Mathematics Examination',
    shortName: 'AIME',
    category: Category.MATHEMATICS,
    description: 'Advanced national competition for top scorers from AMC 10/12.',
    date: 'February 7',
    monthStr: 'February',
    duration: '3 hours',
    language: 'English',
    content: 'Algebra, combinatorics, number theory, geometry.',
    location: 'At participating schools or online.',
    format: 'Individual, short-answer.',
    participation: 'Individual.',
    scoring: 'Each correct answer scores 1 point; top scorers qualify for USA(J)MO.',
    organizer: 'MAA',
    registrationDeadline: 'Invitation Only'
  },
  {
    id: 'math-13',
    name: 'ARML Fall Invitational',
    shortName: 'ARML Fall',
    category: Category.MATHEMATICS,
    description: 'A smaller, early-season ARML event for select schools and teams, emphasizing problem-solving and teamwork.',
    date: 'October',
    monthStr: 'October',
    duration: '3-4 hours',
    language: 'English',
    content: 'Algebra, combinatorics, number theory, geometry, logic.',
    location: 'Selected schools.',
    format: 'Team + Individual + Relay rounds.',
    participation: 'Team; 6 students per team.',
    scoring: 'Points accumulated individually and as a team.',
  },
  {
    id: 'math-14',
    name: 'ARML Regional Competitions',
    shortName: 'ARML Regional',
    category: Category.MATHEMATICS,
    description: 'Regional Competitions allow teams from various states/regions to compete locally, serving as qualifiers for the National Finals.',
    date: 'February - May',
    monthStr: 'February',
    duration: '3-4 hours',
    language: 'English',
    content: 'Algebra, combinatorics, number theory, geometry, logic.',
    location: 'Local/regional sites across the US.',
    format: 'Team + Individual + Relay rounds.',
    participation: 'Team; 6 students per team.',
    scoring: 'Points accumulated individually and as a team.',
  },
  {
    id: 'math-15',
    name: 'ARML National Finals',
    shortName: 'ARML Finals',
    category: Category.MATHEMATICS,
    description: 'Bring together top teams from the Regional Competitions to compete for national recognition.',
    date: 'June',
    monthStr: 'June',
    duration: '3-4 hours',
    language: 'English',
    content: 'Algebra, combinatorics, number theory, geometry, logic.',
    location: 'Usually University of Iowa or online.',
    format: 'Team + Individual + Relay rounds.',
    participation: 'Team; 6 students per team.',
    scoring: 'Points accumulated individually and as a team.',
  },
  {
    id: 'math-16',
    name: 'Carnegie Mellon Informatics and Mathematics Competition',
    shortName: 'CMIMC',
    category: Category.MATHEMATICS,
    description: 'Combines advanced math, computer science, and logic challenges.',
    date: 'March 15',
    monthStr: 'March',
    duration: '3 hours',
    language: 'English',
    content: 'Algebra, combinatorics, number theory, logic, programming.',
    location: 'Online or participating schools.',
    format: 'Individual + Team rounds.',
    participation: 'Team; 4-6 students per team.',
    scoring: 'Based on correct solutions; combined team and individual scores.',
    organizer: 'Carnegie Mellon University',
    registrationDeadline: 'January 30',
    resultDate: 'April'
  },
  {
    id: 'math-17',
    name: 'Math Majors of America Tournament',
    shortName: 'MMATHS',
    category: Category.MATHEMATICS,
    description: 'A national middle school mathematics competition promoting problem-solving, logical thinking, and teamwork.',
    date: 'February-March',
    monthStr: 'February',
    duration: '2-3 hours',
    language: 'English',
    content: 'Algebra, geometry, number theory, combinatorics, reasoning.',
    location: 'Schools and regional centers.',
    format: 'Individual + Team + Countdown Round.',
    participation: 'Team; 1-4 students per team.',
    scoring: 'Individual and team scores combined.',
  },
  {
    id: 'math-18',
    name: 'Math Majors of America Tournament for High Schools',
    shortName: 'GIM (Girls)',
    category: Category.MATHEMATICS,
    description: 'GIM is an online mathematics competition emphasizing creative problem-solving and logical reasoning, accessible to high school students nationwide.',
    date: 'March',
    monthStr: 'March',
    duration: '2 hours',
    language: 'English',
    content: 'Algebra, combinatorics, number theory, geometry, logic.',
    location: 'Online.',
    format: 'Individual.',
    participation: 'Individual (Girls only).',
    scoring: 'Based on number of correct answers.',
  },
  {
    id: 'math-19',
    name: 'Stanford Mathematics Tournament',
    shortName: 'SMT',
    category: Category.MATHEMATICS,
    description: 'National mathematics tournament including multiple rounds, challenging students with proof-based and multiple-choice problems.',
    date: 'April',
    monthStr: 'April',
    duration: '5 hours',
    language: 'English',
    content: 'Algebra, combinatorics, number theory, geometry, proofs.',
    location: 'Stanford University or online.',
    format: 'Individual + Team.',
    participation: 'Team; 6-8 students per team.',
    scoring: 'Individual and team scores combined.',
  },
  {
    id: 'math-20',
    name: 'Berkeley Math Tournament',
    shortName: 'BMT / BMMT',
    category: Category.MATHEMATICS,
    description: 'Regional mathematics competitions for high school students focusing on fast-paced problem-solving and creative thinking.',
    date: 'October/November',
    monthStr: 'October',
    duration: '3 hours',
    language: 'English',
    content: 'Algebra, combinatorics, number theory, geometry, logic.',
    location: 'Respective regional schools/universities.',
    format: 'Individual + Team.',
    participation: 'BMT Team: 6-8 students; BMMT Team: 5 students.',
    scoring: 'Correct answers; team and individual combined scores.',
  },
  {
    id: 'math-21',
    name: 'Harvard-MIT Mathematics Tournament',
    shortName: 'HMMT',
    category: Category.MATHEMATICS,
    description: 'Prestigious tournament emphasizing speed, accuracy, and creativity.',
    date: 'November 18',
    monthStr: 'November',
    duration: '5 hours',
    language: 'English',
    content: 'Algebra, combinatorics, number theory, geometry, logic.',
    location: 'Harvard/MIT or online.',
    format: 'Individual + Team + Guts rounds.',
    participation: 'Team; 6-8 students per team.',
    scoring: 'Points for individual, team, and guts rounds.',
    organizer: 'Harvard & MIT Students',
    registrationDeadline: 'September 30',
    resultDate: 'Same Day'
  },
  {
    id: 'math-22',
    name: 'Princeton University Mathematics Competition',
    shortName: 'PUMaC',
    category: Category.MATHEMATICS,
    description: 'Challenges high school students with individual and team problem-solving in algebra, combinatorics, number theory, and geometry.',
    date: 'November',
    monthStr: 'November',
    duration: '5 hours',
    language: 'English',
    content: 'Algebra, combinatorics, number theory, geometry, logic.',
    location: 'Princeton University or online.',
    format: 'Individual + Team + Power Round.',
    participation: 'Team; 6-8 students per team.',
    scoring: 'Individual, team, and power round combined for awards.',
  },
  {
    id: 'math-23',
    name: 'Johns Hopkins Math Tournament',
    shortName: 'JHMT',
    category: Category.MATHEMATICS,
    description: 'Focuses on creative problem-solving across multiple areas of mathematics for high school students.',
    date: 'August',
    monthStr: 'August',
    duration: '4-5 hours',
    language: 'English',
    content: 'Algebra, combinatorics, number theory, geometry, logic.',
    location: 'Johns Hopkins University or online or offline.',
    format: 'Individual + Team.',
    participation: 'Team; 4 students per team.',
    scoring: 'Combined individual and team scores for awards.',
  },
  {
    id: 'math-24',
    name: 'International Mathematical Modeling Challenge',
    shortName: 'IMMC',
    category: Category.MATHEMATICS,
    description: 'Team-based international competition where high school students use mathematical modeling to solve real-world problems.',
    date: 'November',
    monthStr: 'November',
    duration: '36 hours',
    language: 'English',
    content: 'Applied mathematics, modeling, analysis, report writing.',
    location: 'Online or school-hosted teams.',
    format: 'Team.',
    participation: 'Team; 4 students per team.',
    scoring: 'Based on modeling quality, analysis, and presentation.',
  },
  {
    id: 'math-25',
    name: 'High School Mathematical Contest in Modeling',
    shortName: 'HIMCM',
    category: Category.MATHEMATICS,
    description: 'Challenges high school teams to solve real-world problems using applied mathematics and modeling techniques.',
    date: 'September',
    monthStr: 'September',
    duration: '36-48 hours',
    language: 'English',
    content: 'Mathematical modeling, analysis, report writing.',
    location: 'Online or at school.',
    format: 'Team.',
    participation: 'Team; 4 students per team.',
    scoring: 'Judged on solution accuracy, modeling methodology, and report clarity.',
  },
  {
    id: 'math-26',
    name: 'Digital Math',
    shortName: 'DMMC',
    category: Category.MATHEMATICS,
    description: 'Online mathematics and modeling competition for high school students emphasizing collaborative problem-solving and digital tools.',
    date: 'October',
    monthStr: 'October',
    duration: '3-4 hours',
    language: 'English',
    content: 'Algebra, combinatorics, geometry, applied mathematics, modeling.',
    location: 'Online.',
    format: 'Individual + Team.',
    participation: 'Team; 6 students per team.',
    scoring: 'Based on correct answers, creativity, and team collaboration.',
  },

  // --- Physics ---
  {
    id: 'phy-1',
    name: 'Intermediate Physics Competition',
    shortName: 'IPC',
    category: Category.PHYSICS,
    description: 'International physics competition testing theoretical and experimental problem-solving.',
    date: 'January 15',
    monthStr: 'January',
    duration: 'Varies',
    language: 'English',
    content: 'Mechanics, electricity, magnetism, thermodynamics, optics, waves, modern physics.',
    location: 'Online or designated schools.',
    format: 'Individual + Team; written and experimental rounds.',
    participation: 'Individual.',
    scoring: 'Correct solutions, experimental accuracy, and theoretical reasoning.',
    organizer: 'BPhO'
  },
  {
    id: 'phy-2',
    name: 'Senior Physics Competition',
    shortName: 'SPC',
    category: Category.PHYSICS,
    description: 'National-level competition in Singapore promoting excellence in physics problem-solving.',
    date: 'January',
    monthStr: 'January',
    duration: '3-4 hours',
    language: 'English',
    content: 'Mechanics, electricity, magnetism, thermodynamics, optics, waves, modern physics.',
    location: 'Singapore or online.',
    format: 'Individual + Team; written and experimental rounds.',
    participation: 'Individual.',
    scoring: 'Correct solutions, experimental accuracy, and theoretical reasoning.',
  },
  {
    id: 'phy-3',
    name: 'BAAO Round 1',
    shortName: 'BAAO Junior',
    category: Category.PHYSICS,
    description: 'British Association of Astronomy and Physics Olympiad Round 1. Testing analytical and theoretical problem-solving skills.',
    date: 'October',
    monthStr: 'October',
    duration: '2-3 hours',
    language: 'English',
    content: 'Mechanics, electricity, magnetism, waves, thermodynamics, astronomy.',
    location: 'Online or designated schools.',
    format: 'Individual; written problems.',
    participation: 'Individual.',
    scoring: 'Correct answers; top performers advance to Round 2.',
  },
  {
    id: 'phy-4',
    name: 'BAAO Round 2',
    shortName: 'BAAO Senior',
    category: Category.PHYSICS,
    description: 'Second stage for students qualified from Round 1.',
    date: 'March',
    monthStr: 'March',
    duration: '2-3 hours',
    language: 'English',
    content: 'Advanced mechanics, electricity, magnetism, waves, thermodynamics, astronomy.',
    location: 'Online or designated schools.',
    format: 'Individual; written problems.',
    participation: 'Individual.',
    scoring: 'Correct answers; top performers recognized nationally.',
  },
  {
    id: 'phy-5',
    name: 'British Physics Olympiad Round 1',
    shortName: 'BPHO R1',
    category: Category.PHYSICS,
    description: 'First stage to identify top physics students in the UK.',
    date: 'November 10',
    monthStr: 'November',
    duration: '2-3 hours',
    language: 'English',
    content: 'Mechanics, electricity, magnetism, optics, thermodynamics, waves, modern physics.',
    location: 'Schools, online.',
    format: 'Individual; written theoretical and experimental problems.',
    participation: 'Individual.',
    scoring: 'Correct solutions; top performers advance to Round 2.',
    organizer: 'University of Oxford'
  },
  {
    id: 'phy-6',
    name: 'British Physics Olympiad Round 2',
    shortName: 'BPHO R2',
    category: Category.PHYSICS,
    description: 'For students qualified from Round 1, testing advanced physics problem-solving.',
    date: 'January',
    monthStr: 'January',
    duration: '2-3 hours',
    language: 'English',
    content: 'Advanced mechanics, electricity, magnetism, optics, thermodynamics, waves, modern physics.',
    location: 'Schools, online.',
    format: 'Individual; written theoretical and experimental problems.',
    participation: 'Individual.',
    scoring: 'Correct solutions; top performers recognized nationally.',
  },
  {
    id: 'phy-7',
    name: 'PhysicsBowl',
    shortName: 'PhysicsBowl',
    category: Category.PHYSICS,
    description: 'Nationwide high school physics competition emphasizing multiple-choice problem-solving.',
    date: 'April 5',
    monthStr: 'April',
    duration: '45 minutes',
    language: 'English',
    content: 'Mechanics, thermodynamics, electricity, magnetism, waves, modern physics.',
    location: 'Schools, online.',
    format: 'Individual, multiple-choice.',
    participation: 'Individual.',
    scoring: 'Number of correct answers.',
    organizer: 'AAPT (American Association of Physics Teachers)'
  },
  {
    id: 'phy-8',
    name: 'Princeton University Physics Competition',
    shortName: 'PUPC',
    category: Category.PHYSICS,
    description: 'Challenges high school students with theoretical and experimental physics problems.',
    date: 'November / February',
    monthStr: 'November',
    duration: '1.5 hours',
    language: 'English',
    content: 'Mechanics, electricity, magnetism, thermodynamics, waves, optics, modern physics.',
    location: 'Princeton University or online.',
    format: 'Individual + Team.',
    participation: 'Team; 2-4 students per team.',
    scoring: 'Correctness, reasoning, experimental analysis.',
  },
  {
    id: 'phy-9',
    name: 'Physics Unlimited Explorer Competition',
    shortName: 'PUEC',
    category: Category.PHYSICS,
    description: 'Focuses on open-ended research tasks to develop physics modeling skills, teamwork, and scientific writing.',
    date: 'June',
    monthStr: 'June',
    duration: '2 weeks',
    language: 'English',
    content: 'Open-ended physics research.',
    location: 'Online.',
    format: 'Team; written report.',
    participation: 'Team only; 2-6 students per team.',
    scoring: 'Based on task difficulty, solution quality, research depth.',
  },
  {
    id: 'phy-10',
    name: 'F=ma Exam',
    shortName: 'F=ma',
    category: Category.PHYSICS,
    description: 'First stage of the USA Physics Olympiad (USAPhO) selection process.',
    date: 'February 8',
    monthStr: 'February',
    duration: '75 minutes',
    language: 'English',
    content: 'Mechanics, kinematics, dynamics, energy, momentum.',
    location: 'Schools, online.',
    format: 'Individual, written.',
    participation: 'Individual.',
    scoring: 'Correct answers; top scorers qualify for USAPhO.',
    organizer: 'AAPT'
  },
  {
    id: 'phy-11',
    name: 'USA Physics Olympiad',
    shortName: 'USAPhO',
    category: Category.PHYSICS,
    description: 'Second stage in the USA Physics Olympiad program, selecting top students to represent the USA internationally.',
    date: 'April',
    monthStr: 'April',
    duration: '1.5 hours',
    language: 'English',
    content: 'Mechanics, electricity, magnetism, thermodynamics, waves, optics, modern physics.',
    location: 'Schools, online.',
    format: 'Individual, written.',
    participation: 'Individual.',
    scoring: 'Correctness and methodology.',
  },
  {
    id: 'phy-12',
    name: 'Sir Isaac Newton Contest',
    shortName: 'SIN',
    category: Category.PHYSICS,
    description: 'Emphasizes problem-solving skills in physics for high school students.',
    date: 'April',
    monthStr: 'April',
    duration: '2 hours',
    language: 'English',
    content: 'Mechanics, electricity, magnetism, thermodynamics, waves, modern physics.',
    location: 'Singapore or online.',
    format: 'Individual + Team.',
    participation: 'Individual.',
    scoring: 'Points for correct solutions.',
  },
  {
    id: 'phy-13',
    name: 'Canadian Association of Physicists Competition',
    shortName: 'CAP',
    category: Category.PHYSICS,
    description: 'Emphasizes problem-solving and analytical skills.',
    date: 'April',
    monthStr: 'April',
    duration: '3 hours',
    language: 'English',
    content: 'Mechanics, electricity, magnetism, thermodynamics, waves, modern physics.',
    location: 'Canada or online.',
    format: 'Individual + Team.',
    participation: 'Individual.',
    scoring: 'Points for correct solutions.',
  },
  {
    id: 'phy-14',
    name: 'Asian School Olympiad in Physics',
    shortName: 'ASOP',
    category: Category.PHYSICS,
    description: 'Regional competition for Asian high school students, emphasizing theoretical and problem-solving skills.',
    date: 'October',
    monthStr: 'October',
    duration: '2-3 hours',
    language: 'English',
    content: 'Mechanics, electricity, magnetism, thermodynamics, waves, modern physics.',
    location: 'Online or host schools in Asia.',
    format: 'Individual + Team.',
    participation: 'Individual or Team; 1-4 students per team.',
    scoring: 'Points awarded for correct solutions.',
  },

  // --- Chemistry ---
  {
    id: 'chem-1',
    name: 'Junior Canadian Chemistry Olympiad',
    shortName: 'JCCO',
    category: Category.CHEMISTRY,
    description: 'Designed to ignite enthusiasm and deepen understanding of chemistry among students in grades 8-11.',
    date: 'December',
    monthStr: 'December',
    duration: '1.5 hours',
    language: 'English',
    content: 'Analytical, organic, inorganic, physical chemistry.',
    location: 'Schools or designated exam centers in Japan.',
    format: 'Individual; written + experimental.',
    participation: 'Individual.',
    scoring: 'Correctness, experimental accuracy, and problem-solving methodology.',
  },
  {
    id: 'chem-2',
    name: 'Asian Science Olympiad in Chemistry',
    shortName: 'ASOC',
    category: Category.CHEMISTRY,
    description: 'Regional chemistry competition for high school students across Asia, focusing on theoretical and experimental chemistry.',
    date: 'October',
    monthStr: 'October',
    duration: '2 hours',
    language: 'English',
    content: 'Organic, inorganic, physical chemistry; lab experiments.',
    location: 'Online or host schools in Asia.',
    format: 'Individual + Team; written + experimental.',
    participation: 'Individual or Team; 1-4 students per team.',
    scoring: 'Accuracy, methodology, experimental results.',
  },
  {
    id: 'chem-3',
    name: 'Avogadro Chemistry Competition',
    shortName: 'Avogadro',
    category: Category.CHEMISTRY,
    description: 'International competition targeting high school students, emphasizing problem-solving and lab skills.',
    date: 'May',
    monthStr: 'May',
    duration: '75 minutes',
    language: 'English',
    content: 'Organic, inorganic, physical chemistry.',
    location: 'Schools or online.',
    format: 'Individual + Team.',
    participation: 'Individual or Team; 1-4 students per team.',
    scoring: 'Number of correct answers and problem-solving approach.',
  },
  {
    id: 'chem-4',
    name: 'C3L6 Chemistry Competition',
    shortName: 'C3L6',
    category: Category.CHEMISTRY,
    description: 'Online international chemistry competition for high school students, emphasizing theoretical and applied chemistry.',
    date: 'December',
    monthStr: 'December',
    duration: '90 minutes',
    language: 'English',
    content: 'Organic, inorganic, physical chemistry; problem-solving.',
    location: 'Online.',
    format: 'Individual; written.',
    participation: 'Individual.',
    scoring: 'Correctness and methodology.',
  },
  {
    id: 'chem-5',
    name: 'Canadian Chemistry Challenge',
    shortName: 'CCC',
    category: Category.CHEMISTRY,
    description: 'National competition in Canada emphasizing theoretical chemistry and analytical skills.',
    date: 'April 23',
    monthStr: 'April',
    duration: '1 hour',
    language: 'English/French',
    content: 'Organic, inorganic, physical chemistry; problem-solving.',
    location: 'Schools across Canada.',
    format: 'Individual; written.',
    participation: 'Individual.',
    scoring: 'Number of correct answers and reasoning.',
    organizer: 'Chemical Institute of Canada'
  },
  {
    id: 'chem-6',
    name: 'Canadian Chemistry Olympiad',
    shortName: 'CCO',
    category: Category.CHEMISTRY,
    description: 'The Canadian national chemistry olympiad, selecting top students for IChO participation.',
    date: 'September',
    monthStr: 'September',
    duration: '90 minutes',
    language: 'English/French',
    content: 'Organic, inorganic, physical chemistry; theoretical and experimental.',
    location: 'Schools or designated centers in Canada.',
    format: 'Individual; written + experimental.',
    participation: 'Individual.',
    scoring: 'Correctness, experimental accuracy, methodology.',
  },
  {
    id: 'chem-7',
    name: 'US National Chemistry Olympiad',
    shortName: 'USNCO',
    category: Category.CHEMISTRY,
    description: 'National chemistry olympiad in the USA, selecting students for IChO.',
    date: 'March 20',
    monthStr: 'March',
    duration: '110 minutes',
    language: 'English',
    content: 'Analytical, organic, inorganic, physical chemistry; theoretical and lab problems.',
    location: 'Schools and designated test centers in USA.',
    format: 'Individual; written + lab.',
    participation: 'Individual.',
    scoring: 'Accuracy, experimental results, problem-solving.',
    organizer: 'American Chemical Society'
  },
  {
    id: 'chem-8',
    name: 'UK Chemistry Olympiad',
    shortName: 'UKCHO',
    category: Category.CHEMISTRY,
    description: 'UK national chemistry olympiad selecting top students for IChO.',
    date: 'January 25',
    monthStr: 'January',
    duration: '2 hours',
    language: 'English',
    content: 'Organic, inorganic, physical chemistry; theoretical problems.',
    location: 'Schools in the UK.',
    format: 'Individual; written.',
    participation: 'Individual.',
    scoring: 'Correct answers and problem-solving methodology.',
    organizer: 'Royal Society of Chemistry'
  },
  {
    id: 'chem-9',
    name: 'Chem 13 News Exam',
    shortName: 'Chem 13 News',
    category: Category.CHEMISTRY,
    description: 'Designed for Grade 12 (senior high school) students to assess understanding and application of high school chemistry concepts.',
    date: 'May 9, 2025',
    monthStr: 'May',
    duration: '120 minutes',
    language: 'English',
    content: 'Organic chemistry, equilibrium, kinetics, redox, bonding, etc.',
    location: 'Online.',
    format: 'Individual; multiple-choice.',
    participation: 'By school registration only.',
    scoring: '+1 point for correct answer, -0.25 for wrong answer.',
  },

  // --- Biology ---
  {
    id: 'bio-1',
    name: 'International Brain Bee',
    shortName: 'Brain Bee',
    category: Category.BIOLOGY,
    description: 'Neuroscience competition testing knowledge in neuroanatomy, physiology, and cognitive science.',
    date: 'Jan-March (Regional)',
    monthStr: 'March',
    duration: '1-2 hours per round',
    language: 'English',
    content: 'Human brain structure, function, diseases, neuropharmacology.',
    location: 'Regional, National, International.',
    format: 'Individual; multiple-choice, practical lab, oral.',
    participation: 'Individual.',
    scoring: 'Cumulative across all components.',
    organizer: 'The Brain Bee'
  },
  {
    id: 'bio-2',
    name: 'USA Biology Olympiad',
    shortName: 'USABO',
    category: Category.BIOLOGY,
    description: 'Most prestigious biology competition in the U.S., selecting the national team for IBO.',
    date: 'April 18',
    monthStr: 'April',
    duration: '50 minutes',
    language: 'English',
    content: 'Cell biology, genetics, plant/animal physiology, ecology, evolution.',
    location: 'Online (Open/Semifinal), In-person (Finals).',
    format: 'Individual.',
    participation: 'Through schools.',
    scoring: 'Based on exam and lab results.',
    organizer: 'Center for Excellence in Education'
  },
  {
    id: 'bio-3',
    name: 'British Biology Olympiad',
    shortName: 'BBO',
    category: Category.BIOLOGY,
    description: 'Challenge organized by the Royal Society of Biology.',
    date: 'April 10',
    monthStr: 'April',
    duration: '90 minutes',
    language: 'English',
    content: 'A-level biology, physiology, biochemistry, ecology.',
    location: 'Online.',
    format: 'Individual; multiple-choice.',
    participation: 'Through schools.',
    scoring: 'Percentile-based ranking.',
    organizer: 'Royal Society of Biology'
  },
  {
    id: 'bio-4',
    name: 'Australian Science Olympiad — Biology',
    shortName: 'ASOB',
    category: Category.BIOLOGY,
    description: 'Part of the Australian Science Olympiads, a national qualifying competition for IBO selection.',
    date: 'October',
    monthStr: 'October',
    duration: '2 hours',
    language: 'English',
    content: 'Experimental design, genetics, physiology, plant biology, and ecology.',
    location: 'Online, supervised by teachers.',
    format: 'Individual.',
    participation: 'School registration required.',
    scoring: 'Raw score converted to national percentile.',
  },
  {
    id: 'bio-5',
    name: 'HOSA — Future Health Professionals',
    shortName: 'HOSA',
    category: Category.BIOLOGY,
    description: 'International organization promoting health science education and leadership through competitions and conferences.',
    date: 'Jan-June',
    monthStr: 'January',
    duration: 'Varies',
    language: 'English',
    content: 'Biomedical sciences, anatomy, healthcare issues, public health.',
    location: 'In-person.',
    format: 'Individual and team events.',
    participation: 'Through school HOSA chapters.',
    scoring: 'Written tests and presentations.',
  },
  {
    id: 'bio-6',
    name: 'Canadian Biology Olympiad',
    shortName: 'CBO',
    category: Category.BIOLOGY,
    description: 'Identifies top high school biology students to represent Canada at the IBO.',
    date: 'April',
    monthStr: 'April',
    duration: '2 hours',
    language: 'English or French',
    content: 'Advanced high school and introductory university biology.',
    location: 'Online.',
    format: 'Individual; multiple-choice and short answer.',
    participation: 'Through schools.',
    scoring: 'Cumulative; top scorers invited to training camp.',
  },
  {
    id: 'bio-7',
    name: 'Intermediate Biology Olympiad (UK)',
    shortName: 'IBO (UK)',
    category: Category.BIOLOGY,
    description: 'Designed for pre-university students to bridge between school-level and advanced competitions.',
    date: 'November',
    monthStr: 'November',
    duration: '60 minutes',
    language: 'English',
    content: 'A-level biology and basic university-level topics.',
    location: 'Online.',
    format: 'Individual; multiple-choice.',
    participation: 'Through school registration.',
    scoring: 'Automatic ranking and award tiers.',
  },

  // --- Economics ---
  {
    id: 'econ-1',
    name: 'Wharton Global High School Investment Competition',
    shortName: 'WGHIC',
    category: Category.ECONOMICS,
    description: 'Online investment simulation where students learn finance, teamwork, and strategic decision-making.',
    date: 'Sept - Dec (Comp)',
    monthStr: 'September',
    duration: '3 months',
    language: 'English',
    content: 'Portfolio management, market analysis, teamwork, investment strategy.',
    location: 'Online; Finals at Wharton (USA).',
    format: 'Team-based (4-7 members).',
    participation: 'Teams from schools worldwide.',
    scoring: 'Based on portfolio performance and quality of analysis.',
    organizer: 'Wharton School of Business',
    website: 'https://globalyouth.wharton.upenn.edu/'
  },
  {
    id: 'econ-2',
    name: 'International Economics Olympiad',
    shortName: 'IEO',
    category: Category.ECONOMICS,
    description: 'Annual international competition combining economics, business, and finance challenges for secondary students.',
    date: 'July-August',
    monthStr: 'July',
    duration: '2-5 days',
    language: 'English',
    content: 'Microeconomics, macroeconomics, finance, and case analysis.',
    location: 'Varies yearly.',
    format: 'Combination of individual and team rounds.',
    participation: 'By national qualification.',
    scoring: 'Exam results, business case presentation, and financial literacy test.',
  },
  {
    id: 'econ-3',
    name: 'National Economics Challenge',
    shortName: 'NEC',
    category: Category.ECONOMICS,
    description: 'Top U.S. economics competition testing analytical and policy understanding.',
    date: 'Dec (State) / May (National)',
    monthStr: 'December',
    duration: 'Varies',
    language: 'English',
    content: 'Microeconomics, macroeconomics, international economics.',
    location: 'Online and in-person.',
    format: 'Team-based (4 members).',
    participation: 'Through school teams.',
    scoring: 'Cumulative written and quiz-bowl scores.',
    organizer: 'CEE'
  },
  {
    id: 'econ-4',
    name: 'Student Investment Challenge',
    shortName: 'SIC',
    category: Category.ECONOMICS,
    description: 'Simulates stock trading and portfolio management under real market conditions.',
    date: 'April - June',
    monthStr: 'April',
    duration: '2 months',
    language: 'English',
    content: 'Stock analysis, risk management, investment strategy.',
    location: 'Online.',
    format: 'Team-based (2-4 members).',
    participation: 'Open to global high school students.',
    scoring: 'Portfolio performance and final presentation.'
  },
  {
    id: 'econ-5',
    name: 'Future Business Leaders of America',
    shortName: 'FBLA',
    category: Category.ECONOMICS,
    description: 'Largest business career student organization in the U.S., providing academic competitions and leadership training.',
    date: 'Jan-July',
    monthStr: 'January',
    duration: '60 minutes',
    language: 'English',
    content: 'Business management, finance, entrepreneurship, marketing.',
    location: 'In-person.',
    format: 'Individual and team events.',
    participation: 'Through school FBLA chapters.',
    scoring: 'Written tests, performance, and presentations.',
  },
  {
    id: 'econ-6',
    name: 'DECA Business Competition',
    shortName: 'DECA',
    category: Category.ECONOMICS,
    description: 'Prepares emerging leaders and entrepreneurs in marketing, finance, hospitality, and management.',
    date: 'April',
    monthStr: 'April',
    duration: 'Varies',
    language: 'English',
    content: 'Case studies, business planning, and role-play simulations.',
    location: 'In-person.',
    format: 'Individual and team (2 members).',
    participation: 'Through school DECA chapters.',
    scoring: 'Evaluated by judges based on problem-solving and presentation.',
  },
  {
    id: 'econ-7',
    name: 'Business Professionals of America',
    shortName: 'BPA',
    category: Category.ECONOMICS,
    description: 'U.S.-based organization that hosts academic competitions in business, finance, technology, and marketing.',
    date: 'Dec-March',
    monthStr: 'December',
    duration: 'Varies',
    language: 'English',
    content: 'Accounting, entrepreneurship, business communication.',
    location: 'In-person.',
    format: 'Individual and team (2-4 members).',
    participation: 'Through school BPA chapters.',
    scoring: 'Performance-based evaluation and written testing.',
  },
  {
    id: 'econ-8',
    name: 'Business Plan Competition',
    shortName: 'BPC',
    category: Category.ECONOMICS,
    description: 'Challenges students to develop and pitch innovative business ideas to judges.',
    date: 'Dec-Feb',
    monthStr: 'December',
    duration: 'Varies',
    language: 'English',
    content: 'Entrepreneurship, marketing strategy, and financial modeling.',
    location: 'Online or in-person.',
    format: 'Team-based (2-5 members).',
    participation: 'Open to global high school students.',
    scoring: 'Based on business plan quality and presentation.',
  },
  {
    id: 'econ-9',
    name: 'Harvard International Economics Challenge',
    shortName: 'HIEC',
    category: Category.ECONOMICS,
    description: 'Hosted by the Harvard Undergraduate Economics Association, testing students’ understanding of global economics and policy.',
    date: 'March-May',
    monthStr: 'March',
    duration: 'Varies',
    language: 'English',
    content: 'Microeconomics, macroeconomics, and economic policy case analysis.',
    location: 'Online preliminary; Finals at Harvard University.',
    format: 'Team-based (3-4 members).',
    participation: 'Global school-based registration.',
    scoring: 'Written exams and case presentations.',
  },

  // --- Informatics ---
  {
    id: 'info-1',
    name: 'USA Computing Olympiad',
    shortName: 'USACO',
    category: Category.INFORMATICS,
    description: 'Premier national computing competition preparing for IOI.',
    date: 'Dec - April',
    monthStr: 'December',
    duration: '4-5 hours',
    language: 'English',
    content: 'Algorithm design, data structures, programming problem-solving.',
    location: 'Online.',
    format: 'Individual.',
    participation: 'Individual; open to all.',
    scoring: 'Number of problems solved and efficiency.',
    organizer: 'USACO'
  },
  {
    id: 'info-2',
    name: 'Canadian Computing Competition',
    shortName: 'CCC',
    category: Category.INFORMATICS,
    description: 'Promotes computing and programming skills, organized by University of Waterloo.',
    date: 'February 21',
    monthStr: 'February',
    duration: '3 hours',
    language: 'English',
    content: 'Problem-solving using programming; basic algorithms and logic.',
    location: 'Online or school-based.',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: 'Correctness and efficiency of code.',
    organizer: 'University of Waterloo'
  },
  {
    id: 'info-3',
    name: 'Kaggle Competitions',
    shortName: 'Kaggle',
    category: Category.INFORMATICS,
    description: 'Global platform for data science and ML challenges.',
    date: 'Year-round',
    monthStr: 'January', // Default for year-round
    duration: '1-3 months',
    language: 'English',
    content: 'Machine learning, data analysis, AI model development.',
    location: 'Online.',
    format: 'Individual or Team (up to 5).',
    participation: 'Open to anyone.',
    scoring: 'Leaderboard performance and model accuracy.',
    organizer: 'Google'
  },
  {
    id: 'info-4',
    name: 'American Computer Science League',
    shortName: 'ACSL',
    category: Category.INFORMATICS,
    description: 'Annual international computer science contest consisting of multiple rounds testing algorithmic and theoretical knowledge.',
    date: 'Dec-June',
    monthStr: 'December',
    duration: 'Varies',
    language: 'English',
    content: 'Programming, logic, data representation, digital electronics.',
    location: 'Online or school-hosted.',
    format: 'Individual and Team.',
    participation: 'Teams of 3-5 students.',
    scoring: 'Individual written and programming problem scores.',
  },

  // --- Linguistics ---
  {
    id: 'ling-1',
    name: 'International Linguistics Olympiad',
    shortName: 'IOL',
    category: Category.LINGUISTICS,
    description: 'Solving complex linguistic and logical problems without prior language knowledge.',
    date: 'July 24',
    monthStr: 'July',
    duration: '2 days',
    language: 'English (official)',
    content: 'Logical reasoning, linguistic structure analysis, pattern recognition.',
    location: 'Rotating host countries.',
    format: 'Individual and Team rounds.',
    participation: '4-member national teams.',
    scoring: 'Accuracy and reasoning clarity.'
  },
  {
    id: 'ling-2',
    name: 'John Locke Institute Essay Competition',
    shortName: 'John Locke',
    category: Category.LINGUISTICS,
    description: 'Explores big questions in philosophy, politics, economics, history, etc.',
    date: 'June 30 (Deadline)',
    monthStr: 'June',
    duration: 'Submission based',
    language: 'English',
    content: 'Academic essay writing; analytical and critical argumentation.',
    location: 'Online submission.',
    format: 'Individual.',
    participation: 'Students worldwide.',
    scoring: 'Clarity of argument, originality, depth of analysis.',
    organizer: 'John Locke Institute'
  },
  {
    id: 'ling-3',
    name: 'New York Times Student Editorial Contest',
    shortName: 'NYC Editorial',
    category: Category.LINGUISTICS,
    description: 'Annual competition encouraging students to write persuasive editorials on current issues.',
    date: 'August',
    monthStr: 'August',
    duration: '1 month',
    language: 'English',
    content: 'Persuasive writing, argument structure, evidence-based reasoning.',
    location: 'Online submission.',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: 'Argument strength, clarity, and credible evidence.',
  },
  {
    id: 'ling-4',
    name: 'Harvard International Review Academic Writing Competition',
    shortName: 'HIR',
    category: Category.LINGUISTICS,
    description: 'Invites students to write research essays on international affairs, economics, and global policy.',
    date: 'Spring/Summer/Fall',
    monthStr: 'May',
    duration: 'Submission based',
    language: 'English',
    content: 'Research-based essay writing on global issues.',
    location: 'Online submission.',
    format: 'Individual.',
    participation: 'Individual.',
    scoring: 'Academic rigor, originality, argument coherence.',
  }
];
